### ISSUE TITLE
Unexpected warning when str_c piped with dplyr

### ISSUE THREAD

**Issue by csrvermaak** [hadley/stringr#102]
See Stackoverflow issue [here](http://stackoverflow.com/questions/33689701/mutating-text-using-a-function-in-dplyr)

This works:
```
dates <- tbl_df(data.frame(Dates=c(as.Date("2002-12-31"),as.Date("2003-01-31"))))
getfilename <- function(date) paste0("EQS_",format(date, format="%Y%m%d"),".csv")
expected <- dates %>% mutate(filenames=getfilename(Dates))
```

Result:
```
      Dates        filenames
1 2002-12-31 EQS_20021231.csv
2 2003-01-31 EQS_20030131.csv
```

Now, replacing paste0() with str_c() should work (str_c() is a wrap around paste())
```
dates <- tbl_df(data.frame(Dates=c(as.Date("2002-12-31"),as.Date("2003-01-31"))))
getfilename <- function(date) str_c("EQS_",format(date, format="%Y%m%d"),".csv")
expected<-dates %>%  mutate(filenames=getfilename(Dates))
```

Result: Warning
```
 Warning message:
In mutate_impl(.data, dots) :
  longer object length is not a multiple of shorter object length
```

The difference lies in the paste0/str_c function.

PS - thanks for a great package (and the hadleyverse range of packages! :+1: )

**Comment by gagolews** [comment]
Did you update stringi to 1.0?

**Comment by csrvermaak** [comment]
@gagolews -thank you. The question relates to stringr (not stringi) - or am I missing something?

**Comment by gagolews** [comment]
Yes, stringr is a set of wrappers around stringi. Please update string**I**.

**Comment by csrvermaak** [comment]
I see - ok, thanks, will do that....

**Comment by csrvermaak** [comment]
Hmm... FYI - CRAN says r-release: stringi_1.0-1.zip, but when I install/update from RStudio, I get 0.5-5.

Will install from the tarball, and let you know

**Comment by csrvermaak** [comment]
Updated, getting an error:

```
Error: object 'C_stri_join' not found
```

**Comment by gagolews** [comment]
http://stackoverflow.com/questions/33306592/object-c-stri-join-not-found-using-knitr-in-rstudio,
restart R, reinstall stringi and stringr again (cache...)

**Comment by csrvermaak** [comment]
Works perfectly. Thanks Marek
