### ISSUE TITLE
Unexpected behaviour when using str_replace() in string with a dot "."

### ISSUE THREAD

**Issue by csrvermaak** [hadley/stringr#103]
str_replace seems to randomly replace the first character when trying to replace a "." (might be piping related?)

```
strtest<-"TOP40TR.Index"
str_replace(strtest,".","X")
```

Expected:
```
[1] "TOP40TRXIndex"
```

Actual:
```
[1] "XOP40TR.Index"
```

**Comment by gagolews** [comment]
This is a correct behavior, `str_replace = stri_replace_first_regex`, a regex `.` matches the first character (of any type)

**Comment by csrvermaak** [comment]
Pardon my ignorance. Will read up on regex.

**Comment by csrvermaak** [comment]
PS - How would I replace "." using str_replace()?

**Comment by gagolews** [comment]
fixed(.) AFAIR

**Comment by csrvermaak** [comment]
Thanks Marek - but I don't quite understand :)

**Comment by csrvermaak** [comment]
Got it - 
```
str_replace(strtest,"[.]","X")
```

**Comment by Punitha89** [comment]
How can i replace a part of a string like "from: abc@yahoo.com\n to: abc@gmail.com\n Hi all, \n"
replace "to: abc@gmail.com" with the string with ""

**Comment by Punitha89** [comment]
combination of substring() and gsub() helped me in solving the above issue. Thank you :)

**Comment by nitramwin** [comment]
> Got it -
> 
> ```
> str_replace(strtest,"[.]","X")
> ```

Thanks a bunch for this. I have struggled to find the solution for a week. Now I learned something new. Cheers!
