### ISSUE TITLE
str_count( "(139.004)", "(" )

### ISSUE THREAD

**Issue by aaronvn** [hadley/stringr#105]
Thank your for your great package. But i have some problems when i use stringr, stringi package. 
when i use function str_count( "(139.004)", "(" ) . 

I have an error. Error in stri_count_regex(string, pattern, opts_regex = attr(pattern,  : 
  Incorrectly nested parentheses in regexp pattern. (U_REGEX_MISMATCHED_PAREN)
 I appreciate!

**Comment by gagolews** [comment]
That's a regex match, so parentheses must be escaped, `"\\("`

**Comment by aaronvn** [comment]
Thanks a lot :)
