### ISSUE TITLE
str_detect("", "^.*") == FALSE

### ISSUE THREAD

**Issue by kcandrews** [hadley/stringr#106]
I noticed that `str_detect` behaves differently than `grepl` (at least in the CRAN version) and contrary to the expected behavior for the regular expression `^.*`.

    str_detect("", "^.*") == FALSE
    grepl("^.*", "") == TRUE

**Comment by gagolews** [comment]
This regex has no sense - it's a kind of "undefined behavior"

**Comment by kcandrews** [comment]
I am providing this expression as a default argument to an application facing function that allows users to filter a table based on regular expressions. What `regex` would you suggest that wouldn't filter anything?

**Comment by hadley** [comment]
Maybe `.?` ?

**Comment by kcandrews** [comment]
For me `.?` with `str_detect` still filters out the empty string, which doesn't happen with `grepl`.

**Comment by gagolews** [comment]
Whatever the regex, empty search strings ALWAYS result in FALSE. That's how I implemented that in stringi.

**Comment by gagolews** [comment]
why don't you write:

```
if (!missing(regex)) {
apply_filtering
}
```

of `ii !(iidentical(regex,"")` etc.

**Comment by gagolews** [comment]
OK, I filed an issue for stringi
https://github.com/Rexamine/stringi/issues/214

**Comment by kcandrews** [comment]
I did write something along those lines :) This package is too good not to use. Thanks, for all your wonderful work!

**Comment by gagolews** [comment]
Fixed.
