### ISSUE TITLE
Feature Request: str_wrap Applied Automatically to Factor Levels

### ISSUE THREAD

**Issue by DarioS** [hadley/stringr#107]
If a vector of factors is used with `str_wrap`, it requires effort to compute the new factor levels, particularly to match the level ordering with the previous format. Because `str_wrap` already takes factors as input and produces no error, could it also apply the wrapping to the factor levels, keep their order consistent, and return a factor ?

**Comment by hadley** [comment]
None of the other stringr functions work that way, so I think it would be inconsistent with the rest of string.  It's also easy to write your own helper

```R
str_wrap_factor <- function(x, ...) {
  levels(x) <- str_wrap(levels(x), ...)
  x
}
```
