### ISSUE TITLE
str_replace with replacement=NA replaces all strings

### ISSUE THREAD

**Issue by restonslacker** [hadley/stringr#110]
I had data which contains both "Not Applicable" and `NA`  in the data.  I wanted to make them all `NA`, but ran into issues.  `str_detect` seems to behave differently.

``` r
v <- c("A", "B", NA)
str_detect(v, "A")
#> [1]  TRUE FALSE    NA
str_replace(v, "A", "C")
#> [1] "C" "B" NA
str_replace(v, "A", NA)
#> [1] NA NA NA
str_replace(v, "D", NA)
#> [1] NA NA NA
```
This is using both the CRAN version of `stringr` and the latest version from Github on R 3.2.3 on windows.

**Comment by gagolews** [comment]
This has been very recently  fixed in stringi (https://github.com/Rexamine/stringi/issues/210):

```
> library(stringr)
> v <- c("A", "B", NA)
> str_detect(v, "A")
[1]  TRUE FALSE    NA
> #> [1]  TRUE FALSE    NA
> str_replace(v, "A", "C")
[1] "C" "B" NA 
> #> [1] "C" "B" NA
> str_replace(v, "A", NA)
[1] NA  "B" NA 
> #> [1] NA NA NA
> str_replace(v, "D", NA)
[1] "A" "B" NA 
> #> [1] NA NA NA
```

**Comment by restonslacker** [comment]
Ok.  Confirmed this is fixed if you install the GH version of `stringi`.
Thanks @gagolews for the reply!

``` r
devtools::install_github("Rexamine/stringi")
library(stringr)
v <- c("A", "B", NA)
str_replace(v, "A", NA)
#> [1] NA  "B" NA
```
