### ISSUE TITLE
add value parameter to str_detect

### ISSUE THREAD

**Issue by Deleetdk** [hadley/stringr#111]
`str_detect` usually takes the role of base-r's gsub. However, `gsub` has the parameter value which makes it return the matched values instead of the logicals. This is very useful in some contexts. Compare:

```
gsub(x = data_frame_with_long_name@some_variable, pattern = "[acbde]", value = T)
data_frame_with_long_name@some_variable[str_detect(string = data_frame_with_long_name@some_variable, pattern = "[acbde]")]
```

But it could be simply:

`str_detect(string = data_frame_with_long_name@some_variable, pattern = "[acbde]", value = T)`

**Comment by gagolews** [comment]
In stringi, there's a `stri_subset` function

**Comment by hadley** [comment]
And in stringr there's `str_subset()`.

In general, I think it is a bad idea for an argument to a function to change the return type of the function.
