### ISSUE TITLE
str_count and pattern boundary("character") different from defaut

### ISSUE THREAD

**Issue by cderv** [hadley/stringr#113]
Hi, 

I am not sure to understand why this two commands gives differents results
``` r
library(stringr)
fruit <- c("apple", "banana", "pear", "pineapple")
str_count(fruit, pattern = "")
#> [1] 5 6 4 9
str_count(fruit, pattern = boundary("character"))
#> [1] 0 0 0 0
```

In the help page, it says

> An empty pattern, "", is equivalent to boundary("character").

and more over I expect `boundary("character")` not to give me `0` for each words.

It seems to be a problem in `str_count` or a modification to make in the `str_count` help page.
What do you think?

**Comment by gagolews** [comment]
[note] `stringi` equiv of the above is:

```
> stringi::stri_count_boundaries(c("apple", "banana", "pear", "pineapple"), "character")
[1] 5 6 4 9
```

**Comment by cderv** [comment]
I have the same result.
```r
> stringi::stri_count_boundaries(c("apple", "banana", "pear", "pineapple"), "character")
[1] 5 6 4 9
```
However, when `pattern` arg in `str_count` is of type `bound`, `str_count` dispatch with a `switch` to `stri_count_boundaries(string, opts_brkiter = attr(pattern,  "options"))`: 

```r
function (string, pattern = "") 
{
    switch(type(pattern), empty = stri_count_boundaries(string, 
        opts_brkiter = stri_opts_brkiter(type = "character")), 
        bound = stri_count_boundaries(string, opts_brkiter = attr(pattern, 
            "options")), fixed = stri_count_fixed(string, pattern, 
            opts_fixed = attr(pattern, "options")), coll = stri_count_coll(string, 
            pattern, opts_collator = attr(pattern, "options")), 
        regex = stri_count_regex(string, pattern, opts_regex = attr(pattern, 
            "options")))
}
```

So when `pattern  = boundary("character")` , it is not working with `stringi` either.

``` r
fruit <- c("apple", "banana", "pear", "pineapple")
pattern = stringr::boundary("character")
stringi::stri_count_boundaries(fruit, opts_brkiter = attr(pattern, 
                                                  "options"))
#> [1] 0 0 0 0
attr(pattern, 
     "options")
#> $type
#> [1] "character"
#> 
#> $skip_word_none
#> [1] TRUE
stringi::stri_count_boundaries(fruit, opts_brkiter = list(type = "character", skip_word_none = T))
#> [1] 0 0 0 0
```

However, if I try `skip_word_none = F`, I get the correct result.
```
stringi::stri_count_boundaries(fruit, opts_brkiter = list(type = "character", skip_word_none = F))
#> [1] 5 6 4 9
```

I am not sure to understand what is going on. 
In the help page of `boundary` : 

> `skip_word_none`	Ignore "words" that don't contain any characters or numbers - i.e. punctuation

In the help page of `stri_opts_brkiter`: 

> `skip_word_none` logical; perform no action for "words" that do not fit into any other categories

Is this a bug in `stringr` or is the behaviour normal ?

**Comment by gagolews** [comment]
@hadley `skip_word_none` should default to `FALSE` if `type == 'character'`. In `ICU`, `UBRK_WORD_NONE` should only be used with `type=='word'`.

**Comment by cderv** [comment]
Then maybe change has to made in `boundary` because it is configured with `skip_word_none = TRUE` by default for `type` in `c("character", "line_break", "sentence", "word")`.

Should it be set to `FALSE` by defaut except for `type = "word"` or set to `FALSE` for each and manually set to `TRUE` if user needs it ?

**Comment by gagolews** [comment]
I guess it rather should be omitted in all the cases but `word`

**Comment by hadley** [comment]
Seems to be fixed in dev
