### ISSUE TITLE
Feature request: Function to reverse a string

### ISSUE THREAD

**Issue by ronammar** [hadley/stringr#114]
Can you add a `str_reverse()` function? I cannot find a neat way to reverse a string in R.
Ref: http://stackoverflow.com/questions/13612967/how-to-reverse-a-string-in-r

**Comment by gagolews** [comment]
What for?

```
> stringi::stri_reverse("abcdef")
[1] "fedcba"
```

**Comment by ronammar** [comment]
Convenience - so I only need to load one package

**Comment by gagolews** [comment]
`stringr` imports `stringi` anyway

**Comment by hadley** [comment]
This seems a little too special purpose for stringr to me

**Comment by ronammar** [comment]
When dealing with nucleotide sequences (in bioinformatics), string reversal is a [common task](https://en.wikipedia.org/wiki/Complementarity_(molecular_biology)#DNA_and_RNA_base_pair_complementarity). Perhaps more common than existing functions such as `str_dup()`. While `stringi` does provide this functionality, it would be convenient to wrap it in `stringr` in my opinion.

**Comment by hadley** [comment]
I'd consider a PR, but I'm unlikely to do it myself.

**Comment by jmcastagnetto** [comment]
Just an FYI, there is the [Biostrings](https://www.bioconductor.org/packages/release/bioc/html/Biostrings.html) package in Bioconductor for quite some time, and has functions to deal with reversing sequences. See examples at: https://web.stanford.edu/class/bios221/labs/biostrings/lab_1_biostrings.html and an overview at: https://www.bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/BiostringsQuickOverview.pdf.
The generic `reverse()` function is in the `IRanges` package (https://www.bioconductor.org/packages/release/bioc/manuals/IRanges/man/IRanges.pdf)
