### ISSUE TITLE
error:str_replace_all()

### ISSUE THREAD

**Issue by lixinyao** [hadley/stringr#116]
Hi, I have a problem using `str_replace_all`. Here is a example. It can't replace completely.
```
x = rep("北京链家房地产经纪有限公司",1000000)
y = rep("北京易家房地产经纪有限公司",1000000)
z = c(x,y)
z = str_replace_all(z,c("北京链家房地产经纪有限公司","北京易家房地产经纪有限公司"),"链家")
sum(z=="链家")
[1] 1000000
unique(z)
[1] "链家"                       "北京链家房地产经纪有限公司"
[3] "北京易家房地产经纪有限公司"
```

**Comment by gagolews** [comment]
It is not a bug, it is a feature. This is how recycling rule works in most of the R functions. Try playing with `stringi::stri_replace_all_fixed()`'s `vectorize_all` argument.

**Comment by lixinyao** [comment]
@gagolews Thank you very much!
