### ISSUE TITLE
Feature request: invert option on str_subset and str_detect

### ISSUE THREAD

**Issue by kendonB** [hadley/stringr#117]
Just like ``grep(pat, x, value = TRUE, invert = TRUE)`` / ``grepl(pat, x, invert = TRUE)``.

Or is there already a convenient way to achieve this?

**Comment by gagolews** [comment]
e.g., `stri_detect_regex`, `stri_subset_regex` in `stringi` already have a `negate` argument

**Comment by hadley** [comment]
For `str_detect()`, just use `!`. For `str_subset()` just write your own wrapper.

**Comment by salim-b** [comment]
Just as a reminder for future visitors of this issue: Version 1.4.0 of stringr [introduced the `negate` parameter](https://www.tidyverse.org/articles/2019/02/stringr-1-4-0/)! :tada:
