### ISSUE TITLE
str_detect not implemented

### ISSUE THREAD

**Issue by danielsjf** [hadley/stringr#120]
str_detect('test','') 

Returns a not implemented error. More difficult to find when `''` is hidden in a variable.

**Comment by hadley** [comment]
What do you expect it to do?

**Comment by danielsjf** [comment]
The same as grepl(). Return TRUE if the string is a character (or even always TRUE).

**Comment by danielsjf** [comment]
Some examples 

    > grepl('','hello')
    [1] TRUE
    > grepl('',c('hello','x'))
    [1] TRUE TRUE
    > grepl('',c('hello','x',5))
    [1] TRUE TRUE TRUE
    > grepl('',c(5))
    [1] TRUE
    > grepl('',7)
    [1] TRUE

The last three are more a result of implicit casting to character of the string argument.

**Comment by hadley** [comment]
It's more important for stringr to be internally consistent than to be consistent with base R functions. Currently stringr takes `""` as a shortcut for `boundary("character")`, so I think the correct behaviour would be to return TRUE for strings that have >1 character.

**Comment by gagolews** [comment]
IMO an error is a fine behavior in such a case. 

*problematic when '' is hidden in a variable* -- The error message may be confusing:

```
> stringr::str_detect
function (string, pattern)                                                                                                           
{                                                                                                                                    
    switch(type(pattern), empty = , bound = stop("Not implemented",                                                                                                                          
        call. = FALSE), fixed = stri_detect_fixed(string, pattern,                                                                                                                           
        opts_fixed = attr(pattern, "options")), coll = stri_detect_coll(string,                                                                                                              
        pattern, opts_collator = attr(pattern, "options")), regex = stri_detect_regex(string,                                                                                                
        pattern, opts_regex = attr(pattern, "options")))                                                                                                                                     
}
```

why not replacing  `"Not implemented"` with some more informative msg?
