### ISSUE TITLE
Version of `str_locate` which searches backwards

### ISSUE THREAD

**Issue by thomasjwood** [hadley/stringr#122]
A common use case of `str_sub` and `str_locate` is extracting the last piece of a string delimited by some character.  It gets complicated when the string you're operating on has an inconsistent number of the delimiters. For instance:

      "06/10-15/14"
      "05/11-17/2014"
      "03/14"

I currently solve this by doing a `str_locate_all(fixed("/"))` and then operating on the resulting array to use the last instance of the delimiter to anchor a `str_sub`.

A more elegant solution would be to pass an option to `str_locate` where it searches backwards inside the string.

**Comment by hadley** [comment]
You can also use `stringi::stri_locate_last()`.  I don't want to add this option to stringr as would be a lot of work for relatively little gain.

**Comment by thomasjwood** [comment]
Thanks for the tip, should have checked 'stringi' first!
