### ISSUE TITLE
add preview parameter to str_view automatically 

### ISSUE THREAD

**Issue by dracodoc** [hadley/stringr#125]
@hadley The design of 'stringr' make it easy to just copy and edit lines of str_detect into str_view to check the result. However this is still duplication. 

I think most str_view usage are to preview for other functions, except pure demonstration cases. 

Thus how about adding a 'preview' parameter to other functions like detect, locate which don't show if the results are expected (extract has less problem since the matching result are returned) ? With 'preview = True', there would be an automatic str_view call with same parameters. 

User can set 'preview = debug' (where debug is a varible)  to control the behavior globally easily.

**Comment by hadley** [comment]
I don't like the idea because I strongly believe that parameters shouldn't affect the return type of a function (unless there is a really compelling reason)

**Comment by dracodoc** [comment]
@hadley Oh I was thinking the preview as a side effect in viewer pane (), didn't want to change return type either. Totally agree about the principle.

**Comment by dracodoc** [comment]
@hadley For example, I tried with this (this is just easier to test the side effect and return value):

```
str_detect_preview <- function(string, pattern){
  print(str_view(string, pattern))
  str_detect(string, pattern)
}

str_detect_preview("test detect with preview", "pre")
```

It will show the view in RStudio Viewer pane, also return the same return value as before. When used in Rterm instead of RStudio, the preview html will be opened in browser.

**Comment by hadley** [comment]
I think it's fine if you want to create wrappers like that, but I don't think it's a good idea for stringr.
