### ISSUE TITLE
str_lower, str_upper, str_capitalise, and str_CamelCase

### ISSUE THREAD

**Issue by landroni** [hadley/stringr#27]
Please add functions to convert a character string to all lowercase, all UPPERCASE, all First Letters Of Words In Capitalized Case and all camelCase. You could call the functions: str_lower, str_upper, str_capitalise, and str_CamelCase. 

The first two are more straightforward and should be modeled on the tolower() and toupper() in base R. The last two are more tricky to get right. One source of inspiration could be the tocamel() function in the development version of the 'rapport' package: https://github.com/Rapporter/rapport/tree/development . The associated issues have been partially discussed on r-help: http://r.789695.n4.nabble.com/how-to-transform-string-to-quot-Camel-Case-quot-td4664222.html

Should you decide to take the 'rapport' approach and merge str_capitalise and str_CamelCase into one function, then you could call it str_camel.

**Comment by Tazinho** [comment]
@landroni You might wanna look in the snakecase package, where I implemented a general caseconverter (`to_any_case`), which seems to work very well.

https://github.com/Tazinho/snakecase
