### ISSUE TITLE
NA treatment

### ISSUE THREAD

**Issue by rubenarslan** [hadley/stringr#42]
Often I want str_c (and friends) to behave correspondingly with e.g. sum.

I.e. `sum(NA, 2)` yields NA and I can do `sum(NA, 2, na.rm = T)` to get 2.
`str_c(NA,2)` yields NA2. The shortest way around this, that I've found to yield NA is 
`df[ ,strung_together := ifelse( any( is.na(col1), is.na(col2) ), NA, str_c(col1, col2)]`

So, it would be cool to get `str_c(col1, col2, na.rm = F)` = NA.

**Comment by gagolews** [comment]
BTW, in stringr 1.0.0 we get:

```
> str_c(NA,2)
NA
```
