### ISSUE TITLE
Recommendation: exact match modifier

### ISSUE THREAD

**Issue by ctbrown** [hadley/stringr#55]
I recommend adding an `exact` match modifier like `perl`, `fixed` and `ignore.case`.  

The `exact` modifier should match only on exact matches unlike `fixed` which matches on part of the string. Although this can be done using `==`, the `exact` modifier would allow developers a parallel idiom to switch between exact and less-exact matchings.

An alternative, of course, is to use `perl` with a pattern wrapped between `^` and `$`, but this solutions required applying a function to the pattern and not the string and thus breaking the parallel construction.  

Internally, this could use the `perl` construct described in the preceding paragraph or use the `==`, which should be faster.  

This could probably be implemented -entirely- mostly within the `re_call` function.

**Comment by ctbrown** [comment]
See also #60, which is somewhat related.

**Comment by ctbrown** [comment]
This might not be relevant to the newer `stringi` based release.

**Comment by hadley** [comment]
I think you could now use `stringi::stri_cmp_eq()` for this.
