### ISSUE TITLE
Not working for $

### ISSUE THREAD

**Issue by hshans** [hadley/stringr#56]
This could be a totally dumb question, but I am trying to strip out prices for a set of string using position of a "$". However    str_detect("Jokesonme", "$") gives me TRUE even if there is no "$" in the string.

**Comment by dkahle** [comment]
```$``` is a reserved character, see the ```stringi-search-regex``` link in ```?str_detect```.  This will work instead:

```{R}
str_detect("Jokesonme", fixed("$"))
str_detect("Jokesonme$", fixed("$"))
```

**Comment by hshans** [comment]
Gotcha, Thanks for the quick response.
