### ISSUE TITLE
str_pad() breaks with NAs as input

### ISSUE THREAD

**Issue by petermeissner** [hadley/stringr#59]
The current version of stringr's `str_pad()` (stringr_0.6.2 on R_3.1.3 on Win8) function does behave unexpected in case of `NA` inputs:

    str_pad(NA, 2, "left", 0)
    ## Error in rep.int(string[i], times[i]) : invalid 'times' value

... instead of giving back `NA`.

That beeing said, the current version on Github (via ... 

    devtools::install_github("Rexamine/stringi")
    devtools::install_github("hadley/stringr")

... ) does behave as I would have expected by giving back `NA` output whenever there is `NA` input.

**Comment by gagolews** [comment]
Indeed, with stringr 1.0.0 we have:

```
> str_pad(NA, 2, "left", 0)
[1] NA
```

apparently, this may be closed now.
