### ISSUE TITLE
str_match with non-capturing groups is broken in release version

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/stringr#63]
This minimal case demonstrates the problem (a bunch of non-capturing groups have been appended to make the problem obvious). The problem only occurs when at least one string does not match.

```R
library(magrittr)
library(stringr)

x <- c("A_B_C", "THIS DOES NOT MATCH")
matcher <- regexec("(A)_(B)_(?:C)", x)
matches <- regmatches(x, matcher) %>% print
x %>% str_match("(A)_(B+)_(?:C)(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?")
```

The last line produces this resuit:

```R
> x %>% str_match("(A)_(B+)_(?:C)(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?(?:.)?")
     [,1]    [,2] [,3] [,4]    [,5] [,6] [,7]    [,8] [,9] [,10]   [,11]
[1,] "A_B_C" "A"  "B"  "A_B_C" "A"  "B"  "A_B_C" "A"  "B"  "A_B_C" "A"  
[2,] NA      NA   NA   NA      NA   NA   NA      NA   NA   NA      NA   
Warning message:
In rbind(c("A_B_C", "A", "B"), c(NA_character_, NA_character_, NA_character_,  :
  number of columns of result is not a multiple of vector length (arg 1)
```

The bug is in these lines:

```R
    tmp <- str_replace_all(pattern, "\\\\\\(", "")
    n <- str_length(str_replace_all(tmp, "[^(]", "")) + 1
```

which attempt to count the number of number of capture groups, but fail to exclude non-capturing groups. (Thinking about it, they probably also fail to include a capture group preceded by an even number of backslashes.)

I realize this code has all been replaced by stringi in the devel version, but if you're still maintaining the release version, it would be good to fix this.

**Comment by DarwinAwardWinner** [comment]
I looks like the following code would work instead:

```R
n <- str_split(pattern, "(\\(\\?|\\\\\\[|\\[(?:\\\\\\]|.)*?\\]|\\\\\\(|[^(])+") %>% .[[1]] %>% str_length %>% sum
```

Source: http://stackoverflow.com/a/16047223/125921

**Comment by hadley** [comment]
Is this a still a problem in the dev version?

**Comment by DarwinAwardWinner** [comment]
No, the code in question has been completely replaced with calls to stringi stuff, which gets it right.
