### ISSUE TITLE
str_c with Dates broken in 1.0.0 cran + github 

### ISSUE THREAD

**Issue by szilard** [hadley/stringr#64]
stringr_1.0.0 

> str_c("x",Sys.Date())
[1] "x16556"

 stringr_1.0.0.9000

>  str_c("x",Sys.Date())
[1] "x16556"

stringr_0.6.2

>  str_c("x",Sys.Date())
[1] "x2015-05-01"

**Comment by gagolews** [comment]
Could you please file this bug to https://github.com/Rexamine/stringi/issues?
Luckily, I plan a new stringi release soon.

I guess that `as.character` must be called on all objects with the `class` attribute set, and not the internal `Rf_coerceVector`

**Comment by szilard** [comment]
Sure, done https://github.com/Rexamine/stringi/issues/154

**Comment by gagolews** [comment]
Fixed -----> https://github.com/Rexamine/stringi/issues/154
