### ISSUE TITLE
Implementing a str_elide function for stringr

### ISSUE THREAD

**Issue by ebekebe** [hadley/stringr#65]
I was looking for a elide function that could shorten long strings by replacing the too long middle part by “…”. Since I couldn’t find one for r quickly (I coouldn't find one in the stringi package either), I wrote my own. I think others may also have an interest in that and I would appreciate if you could incorporate it into your package. Below is my implementation (which is public domain licensed).

```R
str_elide = function(s, length = 20, elideText = "...") {
el = str_length(elideText)
l = (length %/% 2) - (el %/% 2)
s1 = str_sub(s, 1, l)
s2 = str_sub(s, str_length(s)-(length-el-l)+1, str_length(s))
s12 = paste0(s1, elideText, s2)
ifelse(str_length(s) > length, s12, s)
}
```

**Comment by hadley** [comment]
I was thinking of `str_trunc()` and adding the parens at the end. I think that suggests we need something that parallels `str_pad()` and has a `side` argument.
