### ISSUE TITLE
Missed stringi dependance

### ISSUE THREAD

**Issue by domanov77** [hadley/stringr#67]
Since now stringr depends on stringi, the latter should be included in the "Depends:" field and not only in the "Imports:" in DESCRIPTION. 
In my case, not having stringi installed, update.packages() failed on stringr.

**Comment by hadley** [comment]
Packages in imports are also automatically installed.

**Comment by domanov77** [comment]
As I said, this is true when installing stringr through install.packages(), not when updating via update.packages(). Possibly an upstream issue. 
Thanks for your incredible work, by the way!
