### ISSUE TITLE
R CMD check failed: The requested ICU resource file cannot be found

### ISSUE THREAD

**Issue by yihui** [hadley/stringr#68]
Travis has been failing but your Travis script failed to capture the failure for some reason: https://travis-ci.org/hadley/stringr/builds/61152178 I noticed it because my knitr repo started to fail after stringr was upgraded (https://travis-ci.org/yihui/knitr/jobs/61492954): 

> The requested ICU resource file cannot be found. Possible problem: ICU data has not been downloaded yet. Call `stri_install_check()`. (U_FILE_ACCESS_ERROR)

stringr has the same error, which I don't completely understand. This may be related to #52.

BTW, you most recent check also failed (for a different reason): https://travis-ci.org/hadley/stringr/builds/61467874 and Travis failed to capture it, either.

**Comment by gagolews** [comment]
This is almost identical to https://github.com/Rexamine/stringi/issues/155

**Comment by hadley** [comment]
@yihui I think the failure might be intermittent

**Comment by yihui** [comment]
@gagolews Oh I did not realize it had been reported. Thanks. But I do not think we have got to the bottom of this issue. It is not necessary to install stringi from Github, either. You just have to install it from source (e.g. the CRAN source package works), and the binary package from marutter's PPA does not work. Well, my experience is that there are quite a few broken binary packages in marutter's PPA...

**Comment by maxheld83** [comment]
I get the sample problem, irrespective of whether `stringr` is loaded from github or CRAN:

```
>     plots <- array.viz(QmethodRes = results)  # produces plots list
Error in stri_trans_nfc(str) : 
  The requested ICU resource file cannot be found. Possible problem: ICU data has not been downloaded yet. Call `stri_install_check()`. (U_FILE_ACCESS_ERROR)
Calls: array.viz -> str_wrap -> stri_wrap -> stri_trans_nfc -> .Call
Execution halted
```

+1 for 
> fix the root cause

Ps.: is it just me or is the 3k-line log from Travis.CI even more confusing than ordinary R CMD check?

**Comment by jeroenooms** [comment]
This is still not resolved. The problem is that `stringi` fails to detect `libicu-dev` on Ubuntu and instead tried to build a bundled version, which doesn't work very well.

**Comment by jeroenooms** [comment]
I have proposed a solution here: https://github.com/Rexamine/stringi/issues/162

**Comment by gagolews** [comment]
Maybe let's first try with debugging the Ubuntu libicu-dev-related issue?

**Comment by gagolews** [comment]
And by the way, the `U_FILE_ACCESS_ERROR` is related to the missing (somehow??) icudt library. If the CRAN guys allowed me to ship icu dt with stringi src package, everything would work like a charm (this would increase the file size by 20MB)...

**Comment by jeroenooms** [comment]
Even if we fix the autoconf check for `libicu-dev` this does not solve the problem of including a bundled ICU that doesn't fully work. If I forget to install `libicu-dev` on my system when installing stringi, I would much prefer that the installation exits with a message that I need to run `apt-get install libicu-dev`, rather than having stringi automatically try to build another copy of ICU. 

If this would have been the case, the problem above would have been obvious from the beginning and this issue would have been resolved much sooner. I cant think of any scenario where you would want to use a DIY version of ICU when a perfectly fine one is available from the OS.

**Comment by gagolews** [comment]
Guys, does a fix to https://github.com/Rexamine/stringi/issues/164 solve the current issue?
