### ISSUE TITLE
Bug in str_subset / fixed

### ISSUE THREAD

**Issue by my-R-help** [hadley/stringr#79]
> str_subset("I", fixed("i", ignore_case = TRUE))
    character(0)

I was expecting to get "I", not the empty string.

**Comment by gagolews** [comment]
@hadley, it's OK in stringi:

```
 > stri_subset_fixed("I", "i", case_insensitive=TRUE)
[1] "I"
```

In `R/subset.R`, line 25, you forgot to add `opts_fixed = attr(pattern, 
"options")`

**Comment by gagolews** [comment]
@hadley, OK, I added a pull request with a fix for that.
