### ISSUE TITLE
Recommendation: Facilitate easier extraction of dates from data

### ISSUE THREAD

**Issue by theRanalyst** [hadley/stringr#81]
## The what:
I'd like to recommend implementing something like the following simple example:
```r
simple_text <- paste("This is an example headline from a local newspaper article.", 
                     "By: John Doe June 10, 2015", sep='\n')
date <- str_extract(simple_text, "%B %d, %Y")
date
[1] "June 10, 2015"
```
## The why:
The `strptime()` function can, of course, achieve this, but I believe being able to extract all dates from a body of text with a function that is already repeatedly being called for text analytics would provide a more streamlined coding process. 

Feel free to just close this if it's something that doesn't seem reasonable or worthwhile.

**Comment by hadley** [comment]
Yeah, this is out of scope for stringr, sorry.
