### ISSUE TITLE
(.*) weird match

### ISSUE THREAD

**Issue by themeo** [hadley/stringr#86]
With the newest version of stringr, (.*) pattern doubles the replacement string:

```
> str_replace_all("A", "(.*)", "ONE(\\1) TWO(\\1) THREE(\\1)")
[1] "ONE(A) TWO(A) THREE(A)ONE() TWO() THREE()"
```

The problem persists in the github versions of stringi and stringr.

**Comment by gagolews** [comment]
stringi's producing this error

**Comment by gagolews** [comment]
OK, it's not a bug, it's a feature. java.util.regex behaves exactly like that, too:

```
Enter your regex: .*
Enter input string to search: A
I found the text "A" starting at index 0 and ending at index 1.
I found the text "" starting at index 1 and ending at index 1.
```

**Comment by hadley** [comment]
I don't think this behaviour is terribly intuitive, but empty matches often have confusing behaviour.
