### ISSUE TITLE
str_split output doesn't match with strsplit

### ISSUE THREAD

**Issue by kismsu** [hadley/stringr#88]
Hi, I wanted to use ``str_split`` as an improved version of ``base::strsplit``, but for my case they have different output:

```
str_split("C-C", "[[:alpha:]]")
[[1]]
[1] ""  "-" "" 
```

```
strsplit("C-C", "[[:alpha:]]")
[[1]]
[1] ""  "-"
```

Is this something expected, and I shouldn't consider the replacement, or this is a bug (or an edge case)?

Thank you

**Comment by gagolews** [comment]
@kismsu, it is a feature in stringi, not a bug. @hadley, if you want compatibility with `strsplit`, I can add an arg to omit the last empty string so that you can incorporate this ft in `stringr`

**Comment by hadley** [comment]
I agree it's a feature too.
