### ISSUE TITLE
Incorrect length/multiple warning

### ISSUE THREAD

**Issue by pitakakariki** [hadley/stringr#90]
The longer object has length 2, which is a multiple of 1, the length of the shorter object.

    > stringr::str_c(c("a", "d"), ".", "c")
    [1] "a.c" "d.c"
    Warning message:
    In stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE) :
      longer object length is not a multiple of shorter object length

Looks like the problem is actually in stringi, but you might want to add this to your unit tests.

**Comment by gagolews** [comment]
already fixed in stringi::stri_c(c("a", "d"), ".", "c") - can be closed
