### ISSUE TITLE
str_replace_all loses names attributes of input vector

### ISSUE THREAD

**Issue by paciorek** [hadley/stringr#92]
Is this intentional?

> text <- c(a = "cat", b = "hat")
> text2 <- str_replace_all(text, "a", "b")
> text2
[1] "cbt" "hbt"
> names(text)
[1] "a" "b"
> names(text2)
NULL

This is in stringr 1.0.0.

**Comment by gagolews** [comment]
Current `stringi` policy is to preserve no attributes. Long time ago I opened an issue (https://github.com/Rexamine/stringi/issues/59), feel free to be the first one joining the discussion.

**Comment by hadley** [comment]
Closing, since discussion needs to happen in stringi.
