### ISSUE TITLE
Documentation: str_extract help page should mention str_match in "See Also"

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/stringr#93]
I was looking for the function to extract capture groups from a regex match, and my first guess was str_extract. I quickly figured out from the help page that this was the wrong choice though. Eventually, I found that the correct one was str_match. But it would have been a lot easier to find if str_extract had led me there by mentioning it in the "See also" section. I think a lot of people probable make the same mistake, finding str_extract when they're looking for str_match, since it's not clear from the names alone which one returns capture groups and which one only returns the complete match.

**Comment by hadley** [comment]
Want to do a pull request?

**Comment by DarwinAwardWinner** [comment]
Sure. I'll do it when I have the time.
