### ISSUE TITLE
Wrong input arguments cause str_sub() to crash the R session

### ISSUE THREAD

**Issue by schmidtchristoph** [hadley/stringr#95]
Dear Hadley and stringr contributors,

This line of code would cause a fatal error and terminate the R session (kids, don't to this at home!):

stringr::str_sub("fatalerror", NA, numeric(0))

It happened to me when I wrote some quick prototype code to extract all characters between a pair of parenthesis. To give an example, this works as expected:

mystr      <- "not interesting chars(something interesting, somethingmore_interesting) not interesting part"

ind1         <- stringr::str_locate(mystr, "\\(")[1,1]
ind2         <- stringr::str_locate_all(mystr, "\\)")[[1]]
ind2         <- ind2[dim(ind2)[1], 1]
mystr_     <- stringr::str_sub(mystr, ind1+1, ind2-1)

However, if the input doesn't contain the pair of parenthesis, e.g. mystr <- "not interesting chars", then the above described situation crops up and str_sub() is called with these unsuitable arguments. Of course, calling the function with illogical input arguments can be easily fixed on the side of the user, but maybe str_sub() should also handle this internally.

Thanks,
Christoph

**Comment by gagolews** [comment]
already fixed in https://github.com/Rexamine/stringi/issues/183
