### ISSUE TITLE
Figure out why roxygen2 tests fail with dev stringr

### ISSUE THREAD

**Issue by hadley** [hadley/stringr#99]
It's something to do with new `str_replace` behaviour

**Comment by hadley** [comment]
Minimal reprex:

```R
str_replace_all('"', '(["\\\\])', "\\\\\\1")
# [1] "\\1"
```

I'm reasonably certain the regular expression is correct, and it should return `'\\"'`  (i.e. the goal is to insert an additional backslash in front of a double quote or backslash)

@gagolews I think this was caused by 4905b0d7f9464bebe3753def9410c73aa4bced7b - I suspect this might not be a problem that regular expressions are well suited to solve, and it might be necessary to implemented a minimal parser in C++ (would need to understand character classes and `\`-escaping)

**Comment by hadley** [comment]
@gagolews just wanted to check if you happened to have built any like this into stringi in the interim. Otherwise I'll start writing up more test cases

**Comment by gagolews** [comment]
```
> sub('(["\\\\])', "\\\\\\1", '"', perl=TRUE)
[1] "\\\""
> 
> sub('(["\\\\])', "\\\\\\1", '"', perl=FALSE)
[1] "\\\""
```

I didn't build anything into stringi like this.

**Comment by hadley** [comment]
This is a somewhat easier to understand reprex:

``` r
library(stringr)
library(stringi)

# OK
str_replace_all("x", "(.)", "\\\\-\\1")
#> [1] "\\-x"
stri_replace_all_regex("x", "(.)", "\\\\-$1")
#> [1] "\\-x"

# NOT OK
str_replace_all("x", "(.)", "\\\\\\1")
#> [1] "\\1"
stri_replace_all_regex("x", "(.)", "\\\\$1")
#> [1] "\\x"
```
